version: '3'
services:
  diamondhandscoin_node1:
    build: .
    cap_add:
      - ALL
    command: diamondhandscoind -server -addnode=172.17.0.1:12345 -addnode=10.7.0.12:12345 -rpcuser=rpc -rpcpassword=x -rpcport=10340  -port=12345 
    networks:
       vpcbr:
          ipv4_address: 10.7.0.11
  diamondhandscoin_node2:
    build: .
    cap_add:
      - ALL
    command: diamondhandscoind -server -addnode=172.17.0.1:12345 -addnode=10.7.0.11:12345 -rpcuser=rpc -rpcpassword=x -rpcport=10340  -port=12345
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
